DROP DATABASE IF EXISTS proyectoFinal;
CREATE DATABASE proyectoFinal;
USE proyectoFinal;

CREATE TABLE USUARIOS(
ID INT PRIMARY KEY UNIQUE NOT NULL AUTO_INCREMENT,
NOMBRE VARCHAR(50) NOT NULL,
APELLIDO1 VARCHAR(50) NOT NULL,
APELLIDO2 VARCHAR(50) NOT NULL,
DIRECCION1 VARCHAR(240) NOT NULL,
TIPO VARCHAR(30) NOT NULL,
CHECK(TIPO='Cliente' OR Tipo='Vendedor' OR Tipo='Administrador')
)